package com.bbva.pisd.lib.r226.util;

public enum CatalogEnum {
    ESTADO_DE_POLIZA("0011"),
    TIPO_DE_CONTACTO("0012"),
    TIPO_DE_UNIDAD("0013"),
    FRECUENCIA_DE_PAGO("0014"),
    INSURANCE_CONTRACT_ENTITY_ID("INSURANCE_CONTRACT_ENTITY_ID"),
    INSURANCE_CONTRACT_BRANCH_ID("INSURANCE_CONTRACT_BRANCH_ID") ,
    INSRC_CONTRACT_INT_ACCOUNT_ID("INSRC_CONTRACT_INT_ACCOUNT_ID") ,
    POLICY_RECEIPT_ID("POLICY_RECEIPT_ID"),
    PREMIUM_PAYMENT_RECEIPT_AMOUNT("PREMIUM_PAYMENT_RECEIPT_AMOUNT"),
    CURRENCY_ID("CURRENCY_ID"),
    INSRNC_CO_RECEIPT_STATUS_TYPE("INSRNC_CO_RECEIPT_STATUS_TYPE"),
    RECEIPT_STATUS_TYPE("RECEIPT_STATUS_TYPE"),
    RENEWAL_RECEIPT_SEQ_NUMBER("RENEWAL_RECEIPT_SEQ_NUMBER"),
    RENEWAL_NUMBER("RENEWAL_NUMBER"),
    RECEIPT_ISSUE_DATE("RECEIPT_ISSUE_DATE"),
    RECEIPT_START_DATE("RECEIPT_START_DATE"),
    RECEIPT_END_DATE("RECEIPT_END_DATE"),
    RECEIPT_EXPIRATION_DATE("RECEIPT_EXPIRATION_DATE"),
    ENTITY_ID("ENTITY_ID"),
    BRANCH_ID("BRANCH_ID"),
    FIRST_VERFN_DIGIT("FIRST_VERFN_DIGIT"),
    SECOND_VERFN_DIGIT("SECOND_VERFN_DIGIT"),
    ACCOUNT_ID("ACCOUNT_ID"),
    INC("INC");

    private final String value;
    CatalogEnum(String value) {this.value = value;}
    public String getValue() { return value; }

}



